In [1]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()
X=[
    {'city':'Beijing'},
    {'city':'Guangzhou'},
    {'city':'Shanghai'}
]
print(onehot_encoder.fit_transform(X).toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
onehot_encoder = OneHotEncoder()
X=[
    {'city':'Beijing'},
    {'city':'Guangzhou'},
    {'city':'Shanghai'}
]
X = pd.DataFrame(X)
print(onehot_encoder.fit_transform(X).toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
X=[
    {'city':1},
    {'city':4},
    {'city':5}
]
onehot_encoder = DictVectorizer()
print(onehot_encoder.fit_transform(X).toarray())

[[1.]
 [4.]
 [5.]]


In [4]:
onehot_encoder = OneHotEncoder()
X=[
    {'city':1},
    {'city':4},
    {'city':5}
]
X = pd.DataFrame(X)
print(onehot_encoder.fit_transform(X).toarray())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
from sklearn import preprocessing
import numpy as np
X = np.array([
    [0., 0., 5., 13., 9., 1.],
    [0., 0., 13., 15., 10., 15.],
    [0., 3., 15., 2., 0., 11.]
])
s = preprocessing.StandardScaler()
print(s.fit_transform(X))

[[ 0.         -0.70710678 -1.38873015  0.52489066  0.59299945 -1.35873244]
 [ 0.         -0.70710678  0.46291005  0.87481777  0.81537425  1.01904933]
 [ 0.          1.41421356  0.9258201  -1.39970842 -1.4083737   0.33968311]]


In [6]:
help(preprocessing.RobustScaler)

Help on class RobustScaler in module sklearn.preprocessing._data:

class RobustScaler(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  RobustScaler(with_centering=True, with_scaling=True, quantile_range=(25.0, 75.0), copy=True)
 |  
 |  Scale features using statistics that are robust to outliers.
 |  
 |  This Scaler removes the median and scales the data according to
 |  the quantile range (defaults to IQR: Interquartile Range).
 |  The IQR is the range between the 1st quartile (25th quantile)
 |  and the 3rd quartile (75th quantile).
 |  
 |  Centering and scaling happen independently on each feature by
 |  computing the relevant statistics on the samples in the training
 |  set. Median and interquartile range are then stored to be used on
 |  later data using the ``transform`` method.
 |  
 |  Standardization of a dataset is a common requirement for many
 |  machine learning estimators. Typically this is done by removing the mean
 |  and scaling to unit variance. Howev

In [7]:
from sklearn.preprocessing import RobustScaler
s = RobustScaler()
print(s.fit_transform(X))

[[ 0.          0.         -1.6         0.          0.         -1.42857143]
 [ 0.          0.          0.          0.30769231  0.2         0.57142857]
 [ 0.          2.          0.4        -1.69230769 -1.8         0.        ]]


In [8]:
corpus = [
    "UNC played Duke in basketball",
    "Duke lost the basketball game"
]
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
print(vectorizer.fit_transform(corpus).todense())
# [[1 1 0 1 0 1 0 1]
# [1 1 1 0 1 0 1 0]]
print(vectorizer.vocabulary_)
# {'unc': 7, 'played': 5, 'duke': 1, 'in': 3, 'basketball': 0, 'lost': 4, 'the': 6, 'game': 2}

[[1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 1 0]]
{'unc': 7, 'played': 5, 'duke': 1, 'in': 3, 'basketball': 0, 'lost': 4, 'the': 6, 'game': 2}


In [9]:
corpus.append("I ate a sandwich and an apple")
print(vectorizer.fit_transform(corpus).todense())
# [[0 0 0 0 1 1 0 1 0 1 0 0 1]
#  [0 0 0 0 1 1 1 0 1 0 0 1 0]
#  [1 1 1 1 0 0 0 0 0 0 1 0 0]]
print(vectorizer.vocabulary_)
# {'unc': 12, 'played': 9, 'duke': 5, 'in': 7, 
#  'basketball': 4, 'lost': 8, 'the': 11, 'game': 6, 
#  'ate': 3, 'sandwich': 10, 'and': 1, 'an': 0, 'apple': 2}

[[0 0 0 0 1 1 0 1 0 1 0 0 1]
 [0 0 0 0 1 1 1 0 1 0 0 1 0]
 [1 1 1 1 0 0 0 0 0 0 1 0 0]]
{'unc': 12, 'played': 9, 'duke': 5, 'in': 7, 'basketball': 4, 'lost': 8, 'the': 11, 'game': 6, 'ate': 3, 'sandwich': 10, 'and': 1, 'an': 0, 'apple': 2}


In [10]:
from sklearn.metrics.pairwise import euclidean_distances
X = vectorizer.fit_transform(corpus).todense()
print("distance between doc1 and doc2 ", euclidean_distances(X[0],X[1]))
print("distance between doc1 and doc3 ", euclidean_distances(X[0],X[2]))
print("distance between doc2 and doc3 ", euclidean_distances(X[1],X[2]))

distance between doc1 and doc2  [[2.44948974]]
distance between doc1 and doc3  [[3.16227766]]
distance between doc2 and doc3  [[3.16227766]]


In [11]:
vectorizer = CountVectorizer(stop_words='english')
print(vectorizer.fit_transform(corpus).todense())
# [[0 0 1 1 0 0 1 0 1]
#  [0 0 1 1 1 1 0 0 0]
#  [1 1 0 0 0 0 0 1 0]]
print(vectorizer.vocabulary_)
# {'unc': 8, 'played': 6, 'duke': 3, 'basketball': 2, 
# 'lost': 5, 'game': 4, 'ate': 1, 'sandwich': 7, 'apple': 0}

[[0 0 1 1 0 0 1 0 1]
 [0 0 1 1 1 1 0 0 0]
 [1 1 0 0 0 0 0 1 0]]
{'unc': 8, 'played': 6, 'duke': 3, 'basketball': 2, 'lost': 5, 'game': 4, 'ate': 1, 'sandwich': 7, 'apple': 0}


In [12]:
corpus = [
    'He ate the sandwiches',
    'Every sandwich was eaten by him'
]
vectorizer = CountVectorizer(binary=True, stop_words='english')
print(vectorizer.fit_transform(corpus).todense())
# [[1 0 1 0]
# [0 1 0 1]]
print(vectorizer.vocabulary_)
# {'ate': 0, 'sandwiches': 2, 'sandwishes': 3, 'eaten': 1}

[[1 0 0 1]
 [0 1 1 0]]
{'ate': 0, 'sandwiches': 3, 'sandwich': 2, 'eaten': 1}


In [14]:
corpus = [
    'I am gathering ingredients for the sandwich.',
    'There were many peoples at the gathering.'
]
from nltk.stem.wordnet import WordNetLemmatizer
# help(WordNetLemmatizer)
lemmatizer = WordNetLemmatizer()
print(lemmatizer.lemmatize('gathering','v')) # gather，动词
print(lemmatizer.lemmatize('gathering','n')) # gathering，名词

gather
gathering


In [19]:
from nltk.stem import PorterStemmer
# help(PorterStemmer)
stemmer = PorterStemmer()
print(stemmer.stem('gathering')) # gather

gather


In [22]:
from nltk import word_tokenize # 取词
from nltk.stem import PorterStemmer # 词干提取
from nltk.stem.wordnet import WordNetLemmatizer # 词性还原
from nltk import pos_tag # 词性标注

wordnet_tags = ['n','v']
corpus = [
    'He ate the sandwiches',
    'Every sandwich was eaten by him'
]
stemmer = PorterStemmer()
print("词干：", [[stemmer.stem(word) for word in word_tokenize(doc)] for doc in corpus])

# 词干： [['He', 'ate', 'the', 'sandwich'], ['everi', 'sandwich', 'wa', 'eaten', 'by', 'him']]

词干： [['He', 'ate', 'the', 'sandwich'], ['everi', 'sandwich', 'wa', 'eaten', 'by', 'him']]


In [25]:
def lemmatize(word, tag):
    if tag[0].lower() in ['n','v']:
        return lemmatizer.lemmatize(word, tag[0].lower())
    return word
lemmatizer = WordNetLemmatizer()
tagged_corpus = [pos_tag(word_tokenize(doc)) for doc in corpus]

print(tagged_corpus)
# [[('He', 'PRP'), ('ate', 'VBD'), ('the', 'DT'), ('sandwiches', 'NNS')], 
#  [('Every', 'DT'), ('sandwich', 'NN'), ('was', 'VBD'), 
#   ('eaten', 'VBN'), ('by', 'IN'), ('him', 'PRP')]]

print('词性还原：',[[lemmatize(word,tag) for word, tag in doc] for doc in tagged_corpus])
# 词性还原： [['He', 'eat', 'the', 'sandwich'], 
#            ['Every', 'sandwich', 'be', 'eat', 'by', 'him']]

[[('He', 'PRP'), ('ate', 'VBD'), ('the', 'DT'), ('sandwiches', 'NNS')], [('Every', 'DT'), ('sandwich', 'NN'), ('was', 'VBD'), ('eaten', 'VBN'), ('by', 'IN'), ('him', 'PRP')]]
词性还原： [['He', 'eat', 'the', 'sandwich'], ['Every', 'sandwich', 'be', 'eat', 'by', 'him']]
