In [10]:
import torch
x = torch.empty(5,3) # 不初始化
print(x)

tensor([[1.0010e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


In [35]:
x = torch.rand(5,3) # 随机初始化
x

tensor([[0.5931, 0.2422, 0.2738],
        [0.0949, 0.4755, 0.7422],
        [0.7418, 0.5980, 0.4837],
        [0.4228, 0.4489, 0.2633],
        [0.7277, 0.7254, 0.8932]])

In [36]:
x = torch.zeros(5,3,dtype=torch.long)
x


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [69]:
x = torch.tensor([[5.5, 3], [2,4]])
x

tensor([[5.5000, 3.0000],
        [2.0000, 4.0000]])

In [73]:
# new_* 方法可以继承之前x的属性，也可以覆盖以前的属性
x = x.new_ones(5,3,dtype=torch.double)
x

x = x.new_zeros(2,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [75]:
x = torch.randn_like(x,dtype=torch.float)
print(x)
print(x.size())

tensor([[ 0.2575, -0.3525,  1.2242, -0.0641],
        [ 0.0307,  0.0433, -0.3609,  2.0844]])
torch.Size([2, 4])


In [83]:
x = torch.eye(3)
y = torch.zeros(3,3)
print(x+y)
print(torch.add(x,y))

res = torch.empty(2,2)
print(res.size())
torch.add(x,y,out=res)
print(res)
print(res.size())

# in-place 加法
y.add_(x) # y = y+x
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([2, 2])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [84]:
print(x[:,:1].size())

x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([3, 1])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [86]:
x = torch.randn(1)
print(x)
print(x.item())

x = torch.randn(2,3)
print(x)
print(x[0,1].item()) # 只能获取一个元素

tensor([1.9585])
1.9585431814193726
tensor([[ 0.4131, -0.6432,  0.4711],
        [-2.1816, -1.3701, -1.9900]])
-0.6431805491447449
