In [35]:
import torch
x = torch.ones(2,2, requires_grad=True)
print(x)
# x.detach_()
# print(x.requires_grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [37]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [38]:
# requires_grad 默认为 False
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
None
True


In [39]:
# out.backward()
print(y.grad)
print(x.grad)
v = torch.tensor(2, dtype=torch.float)
out.backward(v)
print(x.grad)

None
None
tensor([[9., 9.],
        [9., 9.]])


c:\program files\python37\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  


In [40]:
x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm() < 1000:
    y = y*2
print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([995.3259, 310.2364, 944.7957], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [41]:
print(x.requires_grad) # True
print((x ** 2).requires_grad) # True
with torch.no_grad():
    print((x ** 2).requires_grad) # False

True
True
False
